spring:
  datasource:
    url: jdbc:mysql://localhost/mapeo_login
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

